language: python
python:
  - "2.7"
  - "3.6"
# command to install dependencies
install:
  - pip install -r XSteamPython/requirements.txt
  - pip install XSteamPython/.
# command to run tests
script:
  - python tests/tests.py