language: python
python:
  - "2.7"
  - "3.6"
# command to install dependencies
install:
  - pip install XSteamPython/.
  - pip install -r XSteamPython/requirements.txt
# command to run tests
script: tests/tests